/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isp;

public class App {
    public static void main(String[] args) {
        BankPayment bankPayment = new BankPayment();
        LoanPayment loanPayment = new LoanPayment();
    }
}
